#!/usr/bin/env python3
"""Generate the dependency-free Swift and Python Autowifi constants."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config" / "autowifi.json"
SWIFT_PATH = ROOT / "ios" / "Sources" / "AutoWiFiWire" / "GeneratedConstants.swift"
PYTHON_PATH = ROOT / "linux" / "generated_constants.py"


def render_swift(config: dict) -> str:
    bluetooth = config["bluetooth"]
    ios = config["ios"]
    product_discovery_uuids = bluetooth["productDiscoveryUUIDs"]
    legacy_gigabyte_uuids = bluetooth["legacyProductDiscoveryUUIDs"]["gigabyte"]
    legacy_gigabyte_values = "\n".join(
        f'        UUID(uuidString: "{uuid}")!,' for uuid in legacy_gigabyte_uuids
    )
    return f'''// Generated by tools/generate_constants.py. Do not edit.
import Foundation

public enum AutoWiFiConstants {{
    public static let protocolVersion = {config["protocolVersion"]}
    public static let maximumPayloadBytes = {config["maximumPayloadBytes"]}
    public static let serviceUUID = UUID(uuidString: "{bluetooth["serviceUUID"]}")!
    public static let credentialRXUUID = UUID(uuidString: "{bluetooth["credentialRXUUID"]}")!
    public static let statusTXUUID = UUID(uuidString: "{bluetooth["statusTXUUID"]}")!
    public static let productDiscoveryUUIDs = [
        "gigabyte": UUID(uuidString: "{product_discovery_uuids["gigabyte"]}")!,
        "nvidia": UUID(uuidString: "{product_discovery_uuids["nvidia"]}")!,
        "generic": UUID(uuidString: "{product_discovery_uuids["generic"]}")!,
    ]
    public static let legacyGigabyteDiscoveryUUIDs = [
{legacy_gigabyte_values}
    ]
    public static let minimumIOSVersion = "{ios["minimumVersion"]}"
    public static let containerBundleID = "{ios["containerBundleID"]}"
    public static let transportExtensionBundleID = "{ios["transportExtensionBundleID"]}"
}}
'''


def render_python(config: dict) -> str:
    bluetooth = config["bluetooth"]
    ios = config["ios"]
    product_discovery_uuids = bluetooth["productDiscoveryUUIDs"]
    legacy_product_discovery_uuids = bluetooth["legacyProductDiscoveryUUIDs"]
    return f'''# Generated by tools/generate_constants.py. Do not edit.
PROTOCOL_VERSION = {config["protocolVersion"]}
MAXIMUM_PAYLOAD_BYTES = {config["maximumPayloadBytes"]}
SERVICE_UUID = "{bluetooth["serviceUUID"]}"
CREDENTIAL_RX_UUID = "{bluetooth["credentialRXUUID"]}"
STATUS_TX_UUID = "{bluetooth["statusTXUUID"]}"
PRODUCT_DISCOVERY_UUIDS = {product_discovery_uuids!r}
LEGACY_PRODUCT_DISCOVERY_UUIDS = {legacy_product_discovery_uuids!r}
MINIMUM_IOS_VERSION = "{ios["minimumVersion"]}"
CONTAINER_BUNDLE_ID = "{ios["containerBundleID"]}"
TRANSPORT_EXTENSION_BUNDLE_ID = "{ios["transportExtensionBundleID"]}"
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of updating files when generated output is stale",
    )
    args = parser.parse_args()
    config = json.loads(CONFIG_PATH.read_text())
    outputs = {
        SWIFT_PATH: render_swift(config),
        PYTHON_PATH: render_python(config),
    }

    stale = [path for path, content in outputs.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            for path in stale:
                print(f"stale generated file: {path.relative_to(ROOT)}")
            return 1
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
